version: "3"
services:
    # reverse-proxy:
    #     build: ./reverse-proxy/.
    #     image: coding-militia-docker-reverse-proxy:latest
    #     ports:
    #         - "5000:80"
    #         - "5001:5001"
    #     networks:
    #     - overlay
    #     depends_on:
    #         - frontend
    frontend:
        build: ./Frontend/.
        image: smarttasks_web:latest
        container_name: smarttask_web
        # networks:
        #     - overlay
        ports:
            - "8081:80"
        depends_on:
            - backend
    backend:
        build: ./Backend/.
        image: smarttasks_api:latest
        container_name: smarttasks_api
        ports:
            - "8080:80"
        # networks:
        #     - overlay
        # depends_on:
        #     - postgres-db
    # postgres-db:
    #     image: "postgres"
    #     networks:
    #         - overlay
    #     environment:
    #         POSTGRES_USER: "user"
    #         POSTGRES_PASSWORD: "pass"

# networks:
#   overlay: